### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by archigo** [FactorioBlueprints/factorio-prints#144]
Searches seem to be case sensitive. I was trying to look up ore crushers, but got no results on "crusher". "Crusher" did give a few though.

Expected behavior: Searching should not care about upper/lowercase

**Comment by RozeDoyanawa** [comment]
I second this. It is highly annoying as it is now.

**Comment by Bogdanov89** [comment]
Yes please change this, there is no reason for case sensitive search in factorio school.

**Comment by FactorioBlueprints** [comment]
Fixed
