### ISSUE TITLE
Blank grey page on load

### ISSUE THREAD

**Issue by tschmeltzer** [FactorioBlueprints/factorio-prints#366]
Not sure what is wrong, and i hope it's not just a local problem. Or maybe i do as long as the fix is simple.

I get this from chrome:
![image](https://user-images.githubusercontent.com/11270434/132860923-19178f6c-5876-4407-b3f5-7b739bb37775.png)

**Comment by tschmeltzer** [comment]
right at load i briefly see the search bar, but then it blanks.

**Comment by matuuz** [comment]
i'm having the same problem, the only way i could fix it is pressing F5 to reload and ultra fast clicking in the login button, github in this case until the small github window popup appears and then i log in, i don't know what the problem is but i hope it gets fixed soon

**Comment by tschmeltzer** [comment]
@matuuz I'm not fast enough to get it on the login button, but the contact me page also loads normally.

But as far as i can tell the site is not working however you get in

**Comment by FactorioBlueprints** [comment]
Thanks for reporting. I believe the issue is fixed now.

**Comment by tschmeltzer** [comment]
Yep, works now. 👍

**Comment by tschmeltzer** [comment]
@FactorioBlueprints Sorry, I was too fast. the grey screen is still there on the view pages. So I can search, but not click any of them.

**Comment by FactorioBlueprints** [comment]
Ok I think I finally fixed this issue too.

**Comment by tschmeltzer** [comment]
@FactorioBlueprints looks like it :)
