### ISSUE TITLE
Search can't seem to handle zero results

### ISSUE THREAD

**Issue by LukevanTricht** [FactorioBlueprints/factorio-prints#404]
When you search for "Deep Space" in the blueprint search, the page errors out with `Error loading blueprint summaries.`, which I believe is caused by the backend returning this error:
`{
  "code" : 400,
  "message" : "pageNumber is 1 but only retrieved 0 pages"
}`

The backend should probably just return an empty data set when there's no results, instead of returning an error.

**Comment by FactorioBlueprints** [comment]
Thanks for reporting. Fixed it. Please check that it works for you.

**Comment by LukevanTricht** [comment]
Works perfectly, thanks!
