### ISSUE TITLE
Factorio.school tries to request from localhost:8080

### ISSUE THREAD

**Issue by dodgex** [FactorioBlueprints/factorio-prints#458]
I just wanted to search some Blueprints and found a not working page.

When checking devtools for erros i found that the side tries to load content from localhost:

Request URL: http://localhost:8080/api/tags/
Request URL: http://localhost:8080/api/blueprintSummaries/filtered/page/1

**Comment by FactorioBlueprints** [comment]
Thank you for reporting. Rolling back to a working version now.

**Comment by FactorioBlueprints** [comment]
Roll back complete. Should be working now. Thanks again!

**Comment by dodgex** [comment]
Looks good!
