### ISSUE TITLE
Image upload stuck at 100%

### ISSUE THREAD

**Issue by CptToothpick** [FactorioBlueprints/factorio-prints#958]
Tried submitting blueprint -> image stuck at 100%

![image](https://github.com/user-attachments/assets/223d85bc-b359-4bb7-810e-31abd5964500)

**Comment by FactorioBlueprints** [comment]
I have an unrelated bug related to caching the page, and this is causing you to be stuck on an old version. The site no longer has image uploads and requires linking to Imgur instead. Force refresh the page or clear browser caches to fix this issue.
